name: build

on:
  push:
  schedule:
  - cron: '30 2 * * 0'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO: fcrespel
  DOCKER_IMAGE: logstash

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${DOCKER_REGISTRY}
        docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF) .
    - name: Publish image
      run: |
        docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:$(basename $GITHUB_REF)
